server:
  port: 8080

spring:
  application:
    name: "Controle-Vacinacao"
  profiles:
    active: dev

  datasource:
    url: "jdbc:h2:mem:evacina_db"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
  h2:
    console:
      enabled: true
      path: "/h2-console"

