    create table grupos_prioridades_tbl (
       id bigint generated by default as identity,
        descricao varchar(255),
        nome varchar(255),
        primary key (id)
    );

    create table pessoas_tbl (
       id bigint generated by default as identity,
        cpf varchar(255),
        data_nascimento date,
        email varchar(255),
        idade integer,
        nome varchar(255),
        telefone varchar(255),
        is_vacinada boolean,
        id_grupo_prioridade bigint,
        primary key (id)
    );